# configuration for webdriver changed considerably when travis updated
# switched from firefox to CHROMEDRIVER
dist: xenial
addons:
  chrome: stable
# changes for xvfb required for xenial as per https://docs.travis-ci.com/user/gui-and-headless-browsers/
services:
  - xvfb
install:
  # hacking in stuff from seleniumhq https://github.com/SeleniumHQ/selenium/blob/master/.travis.yml
  #                                  https://github.com/SeleniumHQ/selenium/blob/master/scripts/travis/install.sh
  # install chromedriver
  - export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
language: java
script:
# FIREFOX Driver requires additional install
# - mvn -f code/pom.xml test -Dselenium2basics.webdriver=FIREFOXLEGACY
- mvn -f code/pom.xml test -Dselenium2basics.webdriver=HTMLUNIT
- xvfb-run -e /dev/stdout --auto-servernum --server-args="-screen 0 1024x768x24" mvn -f code/pom.xml test -Dselenium2basics.webdriver=GOOGLECHROME
jdk:
  - oraclejdk11
  - openjdk8
  - openjdk10
  - openjdk11
